### ISSUE TITLE
MySQL instead of MariaDB

### ISSUE THREAD

**Issue by pczerkas** [tigerlinux/openstack-kilo-installer-ubuntu1404lts#2]
Hello,

Is it possible to add an option allowing for MySQL installation instead of MariaDB? There are issues when there is a need to install for example PHP5 Dependencies while having MariaDB installed:
http://askubuntu.com/questions/653785/how-can-i-build-php5-dependencies-while-having-mariadb-installed

**Comment by tigerlinux** [comment]
Hi there,
Sorry but we changed our support to mariadb long ago !. As you probably know, many linux distributions has been doing the same (making mariadb as primary MySQL replacement) so we are doing the same.
If you want to change to mysql, you will need to modify the installer. The file you need to modify is:
./modules/databaseinstall.sh.

Best regards,

TigerLinux
