### ISSUE TITLE
HA support?

### ISSUE THREAD

**Issue by kkxue** [tigerlinux/openstack-kilo-installer-ubuntu1404lts#3]
Hi,does your scripts support  openstack High Available mode deploy?
just like this repo did:
https://github.com/wingon-niu/OpenStackDeploy

**Comment by tigerlinux** [comment]
Hi there,

Nope. The public version of my scripts are not designed for H.A. I had internall "modified" versions, but are intended for business use in my job-environment.

Yo can modify the scripts and make them H.A. !. Those are just shell scripts with non-ofuscated code !. If you know how to deploy OpenStack in an H.A. way (the guide at docs.openstack.org is a good start), you'll know what to modify !.

For a start: H.A. firts the backends (database, message broker, and if you can, the storage backends... "ceph" is the BEST OF THE BEST of all Storage options for OpenStack). Put both DB and Message Broker behind VIP's (balanced of course).

Best regards,

TigerLinux.
