### ISSUE TITLE
Scripts Fails

### ISSUE THREAD

**Issue by brahmastra2016** [tigerlinux/openstack-kilo-installer-ubuntu1404lts#4]
the script fails to execute with below error trying to executing keystone command , i found that we need to update the apt source.

**Error:**

Creating Keystone Service Endpoint
usage: openstack service create [-h] [-f {html,json,shell,table,yaml}]
                                [-c COLUMN] [--variable VARIABLE]
                                [--prefix PREFIX] --type <service-type>
                                [--description <service-description>]
                                <service-name>
openstack service create: error: argument --type is required 

**Fix:**

sudo add-apt-repository cloud-archive:kilo
sudo apt-get update**

**Comment by tigerlinux** [comment]
Hi there,

Thanks for the info. Sadly, I wont fix this as kilo was set EOL (end-of-life) and I can't assure quality on my installers if the base version is not being maintained. Current EOL versions goes from diablo up to liberty. Please try to use the last OpenStack versions that are still very well supported: Ocata, Newton (Mitaka will go to EOL soon too).
